# Forward problem (operator A) parameters
k: 3
sigma: 1.3
kernel_type: 'gaussian'

# Training parameters
learning_rate: 0.0005
n_epochs: 50
batch_size: 8

# StNN
stnn:
  reg_param: 0.01
  n_iter: 3

# StReNN
stnn:
  reg_param: 0.01
  n_iter: 3